jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./C:\Users\sandi\Documents\B.Tech\3-1\CICD\insem1\carrental-frontend-main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: carrental-frontend-main/build/
